import { Manrope} from "next/font/google";
import "./globals.css";
import Footer from "./components/shared/Footer";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});


export const metadata = {
  title: "Ema Ena",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} antialiased`}
      >
        <div className="min-h-screen">
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
